### ISSUE TITLE
STRING / Que dos Strings distintos se repitan x veces

### ISSUE THREAD

**Issue by Mel-Gr** [Mel-Gr/DAW-Entornos-P10-Carol#15]
Tiene que devolver un string con los dos strings repetidos tantas veces como se indique

**Comment by Mel-Gr** [comment]
Se ha borrado con los commits de después. Haz primero un pull de la rama dev, y luego lo vuelves a poner porfi

**Comment by 0T4KU1312** [comment]
okey ahora lo hago .
